# Generated by Django 5.2.11 on 2026-02-04 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_task_created_at_tag_task_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("completed", "Completed"),
                    ("deleted", "Deleted"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
